import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service'; import { AuthUser } from '../auth/auth.types'; import { MessagingProviderService } from './messaging-provider.service';
@Injectable() export class MessagingService { constructor(private db:DatabaseService,private provider:MessagingProviderService){}
 private allowed(u:AuthUser){if(!['ADMIN','MANAGER'].includes(u.role))throw new ForbiddenException('Messaging is available to Admin and Manager only');}
 private channel(v:any):'WHATSAPP'|'SMS'{const c=String(v||'WHATSAPP').toUpperCase();if(c!=='WHATSAPP'&&c!=='SMS')throw new BadRequestException('Invalid channel');return c;}
 private ids(v:any):string[]{if(v==null)return [];if(!Array.isArray(v))throw new BadRequestException('selectedCustomerIds must be an array');return [...new Set(v.map(String).filter(Boolean))];}
 private async customer(id:string){const r=await this.db.query<any>('SELECT id,name,phone,whatsapp_opt_in,sms_opt_in FROM customers WHERE id=$1 AND active=true',[id]);if(!r.rowCount)throw new NotFoundException('Customer not found');if(!r.rows[0].phone)throw new BadRequestException('Customer has no phone number');return r.rows[0];}
 private async conversation(customerId:string,channel:string){return (await this.db.query<any>(`INSERT INTO message_conversations(customer_id,channel) VALUES($1,$2) ON CONFLICT(customer_id,channel) DO UPDATE SET status='OPEN' RETURNING id`,[customerId,channel])).rows[0];}
 async updateConsent(u:AuthUser,customerId:string,b:any){this.allowed(u);const c=await this.customer(customerId);const wa=typeof b.whatsappOptIn==='boolean'?b.whatsappOptIn:c.whatsapp_opt_in;const sms=typeof b.smsOptIn==='boolean'?b.smsOptIn:c.sms_opt_in;const r=(await this.db.query<any>(`UPDATE customers SET whatsapp_opt_in=$2,sms_opt_in=$3,whatsapp_opt_in_at=CASE WHEN $2 THEN COALESCE(whatsapp_opt_in_at,now()) ELSE NULL END,sms_opt_in_at=CASE WHEN $3 THEN COALESCE(sms_opt_in_at,now()) ELSE NULL END WHERE id=$1 RETURNING id,name,phone,whatsapp_opt_in,sms_opt_in,whatsapp_opt_in_at,sms_opt_in_at`,[customerId,wa,sms])).rows[0];await this.db.query(`INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'CUSTOMER_MESSAGING_CONSENT_UPDATED','CUSTOMER',$2,$3)`,[u.sub,customerId,JSON.stringify({whatsappOptIn:wa,smsOptIn:sms})]);return r;}
 async history(u:AuthUser,customerId:string){this.allowed(u);return (await this.db.query(`SELECT id,channel,direction,body,media_url,status,failure_reason,created_at,delivered_at,read_at FROM messages WHERE customer_id=$1 ORDER BY created_at`,[customerId])).rows;}
 async send(u:AuthUser,customerId:string,b:any){this.allowed(u);const channel=this.channel(b.channel);const body=String(b.body||'').trim(),mediaUrl=String(b.mediaUrl||'').trim()||null;if(!body&&!mediaUrl)throw new BadRequestException('Message or image is required');if(channel==='SMS'&&mediaUrl)throw new BadRequestException('Image sending is supported through WhatsApp');const c=await this.customer(customerId);if(channel==='WHATSAPP'&&!c.whatsapp_opt_in)throw new BadRequestException('Customer has not opted in to WhatsApp messages');if(channel==='SMS'&&!c.sms_opt_in)throw new BadRequestException('Customer has not opted in to SMS messages');const conv=await this.conversation(customerId,channel);const msg=(await this.db.query<any>(`INSERT INTO messages(conversation_id,customer_id,channel,direction,body,media_url,created_by) VALUES($1,$2,$3,'OUTBOUND',$4,$5,$6) RETURNING *`,[conv.id,customerId,channel,body||null,mediaUrl,u.sub])).rows[0];try{const out=channel==='WHATSAPP'?await this.provider.sendWhatsApp(c.phone,body,mediaUrl??undefined):await this.provider.sendSms(c.phone,body);await this.db.query(`UPDATE messages SET status='SENT',provider_message_id=$2 WHERE id=$1`,[msg.id,out.providerMessageId]);await this.db.query('UPDATE message_conversations SET last_message_at=now() WHERE id=$1',[conv.id]);return {...msg,status:'SENT',provider_message_id:out.providerMessageId};}catch(e:any){await this.db.query(`UPDATE messages SET status='FAILED',failure_reason=$2 WHERE id=$1`,[msg.id,String(e?.message||'Send failed')]);throw e;}}
 async previewBulk(u:AuthUser,b:any){this.allowed(u);const channel=this.channel(b.channel), selected=this.ids(b.selectedCustomerIds);const opt=channel==='WHATSAPP'?'whatsapp_opt_in':'sms_opt_in';const p:any[]=[];let selectedSql='';if(selected.length){p.push(selected);selectedSql=' AND id = ANY($1::uuid[])';}const r=await this.db.query<any>(`SELECT id,name,phone FROM customers WHERE active=true AND phone IS NOT NULL AND ${opt}=true${selectedSql} ORDER BY name`,p);return {channel,recipientCount:r.rowCount,recipients:r.rows.map((x:any)=>({id:x.id,name:x.name}))};}
 async createCampaign(u:AuthUser,b:any){this.allowed(u);const channel=this.channel(b.channel),title=String(b.title||'').trim(),body=String(b.body||'').trim(),media=String(b.mediaUrl||'').trim()||null,selected=this.ids(b.selectedCustomerIds);if(!title||(!body&&!media))throw new BadRequestException('Title and message or image are required');if(channel==='SMS'&&media)throw new BadRequestException('SMS campaign cannot contain image');const opt=channel==='WHATSAPP'?'whatsapp_opt_in':'sms_opt_in';return this.db.transaction(async c=>{const campaign=(await c.query<any>(`INSERT INTO message_campaigns(channel,title,body,media_url,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[channel,title,body||null,media,u.sub])).rows[0];const p:any[]=[];let selectedSql='';if(selected.length){p.push(selected);selectedSql=' AND id = ANY($1::uuid[])';}const recipients=await c.query<any>(`SELECT id FROM customers WHERE active=true AND phone IS NOT NULL AND ${opt}=true${selectedSql}`,p);for(const x of recipients.rows)await c.query('INSERT INTO message_campaign_recipients(campaign_id,customer_id) VALUES($1,$2)',[campaign.id,x.id]);await c.query('UPDATE message_campaigns SET recipient_count=$2 WHERE id=$1',[campaign.id,recipients.rowCount]);return {...campaign,recipient_count:recipients.rowCount,requiresConfirmation:true};});}
 async confirmCampaign(u:AuthUser,id:string){this.allowed(u);const camp=(await this.db.query<any>(`UPDATE message_campaigns SET status='CONFIRMED',confirmed_by=$2,confirmed_at=now() WHERE id=$1 AND status='DRAFT' RETURNING *`,[id,u.sub])).rows[0];if(!camp)throw new BadRequestException('Campaign not found or already confirmed');const opt=camp.channel==='WHATSAPP'?'whatsapp_opt_in':'sms_opt_in';const rs=await this.db.query<any>(`SELECT r.customer_id,c.phone,c.${opt} opted_in,c.active FROM message_campaign_recipients r JOIN customers c ON c.id=r.customer_id WHERE r.campaign_id=$1 AND r.status='PENDING'`,[id]);let sent=0,failed=0;await this.db.query(`UPDATE message_campaigns SET status='SENDING' WHERE id=$1`,[id]);for(const r of rs.rows){if(!r.active||!r.opted_in||!r.phone){await this.db.query(`UPDATE message_campaign_recipients SET status='SKIPPED',failure_reason='Customer unavailable or opted out before send' WHERE campaign_id=$1 AND customer_id=$2`,[id,r.customer_id]);continue;}let msg:any=null;try{const conv=await this.conversation(r.customer_id,camp.channel);msg=(await this.db.query<any>(`INSERT INTO messages(conversation_id,customer_id,channel,direction,body,media_url,created_by) VALUES($1,$2,$3,'OUTBOUND',$4,$5,$6) RETURNING id`,[conv.id,r.customer_id,camp.channel,camp.body,camp.media_url,u.sub])).rows[0];const out=camp.channel==='WHATSAPP'?await this.provider.sendWhatsApp(r.phone,camp.body,camp.media_url):await this.provider.sendSms(r.phone,camp.body);await this.db.query(`UPDATE messages SET status='SENT',provider_message_id=$2 WHERE id=$1`,[msg.id,out.providerMessageId]);await this.db.query(`UPDATE message_conversations SET last_message_at=now() WHERE id=$1`,[conv.id]);await this.db.query(`UPDATE message_campaign_recipients SET status='SENT',message_id=$3 WHERE campaign_id=$1 AND customer_id=$2`,[id,r.customer_id,msg.id]);sent++;}catch(e:any){failed++;const reason=String(e?.message||'Send failed');if(msg)await this.db.query(`UPDATE messages SET status='FAILED',failure_reason=$2 WHERE id=$1`,[msg.id,reason]);await this.db.query(`UPDATE message_campaign_recipients SET status='FAILED',failure_reason=$3,message_id=COALESCE($4,message_id) WHERE campaign_id=$1 AND customer_id=$2`,[id,r.customer_id,reason,msg?.id||null]);}}
 const status=failed===0?'COMPLETED':sent===0?'FAILED':'PARTIAL';return (await this.db.query<any>(`UPDATE message_campaigns SET status=$2,sent_count=$3,failed_count=$4,completed_at=now() WHERE id=$1 RETURNING *`,[id,status,sent,failed])).rows[0];}
 async listCampaigns(u:AuthUser){this.allowed(u);return (await this.db.query(`SELECT id,channel,title,status,recipient_count,sent_count,failed_count,created_at,completed_at FROM message_campaigns ORDER BY created_at DESC LIMIT 50`)).rows;}
}
