import {Injectable,BadRequestException,NotFoundException} from '@nestjs/common';import {DatabaseService} from '../database/database.service';
const TYPES=['ABOUT','PRODUCT','ANNOUNCEMENT','CONTACT','HERO'];
@Injectable() export class WebsiteContentService{constructor(private db:DatabaseService){}
 private clean(b:any){if(b.contentType!==undefined&&!TYPES.includes(b.contentType))throw new BadRequestException('Invalid public content type');if(b.publicPrice!==undefined&&b.publicPrice!==null&&(!Number.isFinite(Number(b.publicPrice))||Number(b.publicPrice)<0))throw new BadRequestException('Public price must be zero or greater');if(b.imageUrl&&!(String(b.imageUrl).startsWith('data:image/')||String(b.imageUrl).startsWith('https://')||String(b.imageUrl).startsWith('/')))throw new BadRequestException('Image must be an uploaded image or safe public URL');return b}
 async publicContent(){return (await this.db.query(`SELECT id,content_type,title,body,image_url,public_price,sort_order,published_at FROM website_content WHERE status='PUBLISHED' ORDER BY content_type,sort_order,published_at DESC`)).rows}
 async adminList(){return (await this.db.query(`SELECT id,content_type,title,body,image_url,public_price,status,sort_order,published_at,created_at,updated_at FROM website_content ORDER BY updated_at DESC`)).rows}
 async preview(id:string){const r=await this.db.query(`SELECT id,content_type,title,body,image_url,public_price,status,sort_order,published_at FROM website_content WHERE id=$1`,[id]);if(!r.rowCount)throw new NotFoundException('Website content not found');return r.rows[0]}
 async create(body:any,user:any){this.clean(body);if(!body?.title?.trim()||!body?.contentType)throw new BadRequestException('Title and content type are required');return this.db.transaction(async c=>{const r=await c.query<any>(`INSERT INTO website_content(content_type,title,body,image_url,public_price,status,sort_order,created_by,updated_by) VALUES($1,$2,$3,$4,$5,'DRAFT',$6,$7,$7) RETURNING *`,[body.contentType,body.title.trim(),body.body||null,body.imageUrl||null,body.publicPrice??null,Number(body.sortOrder)||0,user.sub]);await c.query(`INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'WEBSITE_CONTENT_CREATED','WEBSITE_CONTENT',$2,$3)`,[user.sub,r.rows[0].id,JSON.stringify({contentType:body.contentType,title:body.title})]);return r.rows[0]})}
 async update(id:string,b:any,user:any){this.clean(b);return this.db.transaction(async c=>{const old=await c.query<any>('SELECT * FROM website_content WHERE id=$1 FOR UPDATE',[id]);if(!old.rowCount)throw new NotFoundException('Website content not found');const r=await c.query<any>(`UPDATE website_content SET title=COALESCE($2,title),body=CASE WHEN $3::boolean THEN $4 ELSE body END,image_url=CASE WHEN $5::boolean THEN $6 ELSE image_url END,public_price=CASE WHEN $7::boolean THEN $8 ELSE public_price END,sort_order=COALESCE($9,sort_order),updated_by=$10,updated_at=now() WHERE id=$1 RETURNING *`,[id,b.title??null,'body' in b,b.body??null,'imageUrl' in b,b.imageUrl??null,'publicPrice' in b,b.publicPrice??null,b.sortOrder??null,user.sub]);await c.query(`INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'WEBSITE_CONTENT_UPDATED','WEBSITE_CONTENT',$2,$3)`,[user.sub,id,JSON.stringify({title:r.rows[0].title})]);return r.rows[0]})}
 async publish(id:string,publish:boolean,user:any){return this.db.transaction(async c=>{const r=await c.query<any>(`UPDATE website_content SET status=$2,published_at=CASE WHEN $2='PUBLISHED' THEN now() ELSE published_at END,updated_by=$3,updated_at=now() WHERE id=$1 RETURNING *`,[id,publish?'PUBLISHED':'UNPUBLISHED',user.sub]);if(!r.rowCount)throw new NotFoundException('Website content not found');await c.query(`INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'WEBSITE_CONTENT',$3,$4)`,[user.sub,publish?'WEBSITE_CONTENT_PUBLISHED':'WEBSITE_CONTENT_UNPUBLISHED',id,JSON.stringify({title:r.rows[0].title})]);return r.rows[0]})}}
