import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service'; import { AuthUser } from '../auth/auth.types';
@Injectable() export class CustomersService { constructor(private db:DatabaseService){}
 async create(b:any){const name=String(b.name||'').trim(),phone=String(b.phone||'').trim()||null;if(!name)throw new BadRequestException('Customer name is required');try{return (await this.db.query('INSERT INTO customers(name,phone) VALUES($1,$2) RETURNING id,name,phone,active',[name,phone])).rows[0];}catch(e:any){if(e?.code==='23505')throw new BadRequestException('A customer with this phone already exists');throw e;}}
 async update(id:string,b:any){const current=(await this.db.query<any>('SELECT * FROM customers WHERE id=$1',[id])).rows[0];if(!current)throw new NotFoundException('Customer not found');const name=b.name===undefined?current.name:String(b.name).trim();if(!name)throw new BadRequestException('Customer name is required');const phone=b.phone===undefined?current.phone:(String(b.phone||'').trim()||null);const active=b.active===undefined?current.active:!!b.active;try{return (await this.db.query('UPDATE customers SET name=$2,phone=$3,active=$4,updated_at=now() WHERE id=$1 RETURNING id,name,phone,active',[id,name,phone,active])).rows[0];}catch(e:any){if(e?.code==='23505')throw new BadRequestException('A customer with this phone already exists');throw e;}}
 async list(){return (await this.db.query(`SELECT c.id,c.name,c.phone,c.active,c.whatsapp_opt_in,c.sms_opt_in,COALESCE(a.credit_balance,0) credit_balance,COALESCE((SELECT SUM(s.debt_remaining) FROM sales s WHERE s.customer_id=c.id AND s.status='CONFIRMED'),0) debt_balance FROM customers c LEFT JOIN customer_accounts a ON a.customer_id=c.id ORDER BY c.name`)).rows;}
 async account(id:string){const r=await this.db.query(`SELECT c.id,c.name,c.phone,c.active,c.whatsapp_opt_in,c.sms_opt_in,COALESCE(a.credit_balance,0) credit_balance,COALESCE(SUM(s.debt_remaining),0) debt_balance FROM customers c LEFT JOIN customer_accounts a ON a.customer_id=c.id LEFT JOIN sales s ON s.customer_id=c.id AND s.status='CONFIRMED' WHERE c.id=$1 GROUP BY c.id,a.credit_balance`,[id]);if(!r.rowCount)throw new NotFoundException('Customer not found');const payments=(await this.db.query(`SELECT id,amount,created_at FROM customer_payments WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 20`,[id])).rows;const openDebts=(await this.db.query(`SELECT id,sale_number,debt_remaining,created_at FROM sales WHERE customer_id=$1 AND status='CONFIRMED' AND debt_remaining>0 ORDER BY created_at`,[id])).rows;return {...r.rows[0],payments,openDebts};}
 async payDebt(user:AuthUser,id:string,raw:any){const amount=Number(raw);if(!(amount>0))throw new BadRequestException('Payment must be greater than zero');return this.db.transaction(async c=>{const customer=await c.query('SELECT id FROM customers WHERE id=$1 AND active=true FOR UPDATE',[id]);if(!customer.rowCount)throw new NotFoundException('Customer not found');await c.query('INSERT INTO customer_accounts(customer_id,credit_balance) VALUES($1,0) ON CONFLICT(customer_id) DO NOTHING',[id]);await c.query('SELECT credit_balance FROM customer_accounts WHERE customer_id=$1 FOR UPDATE',[id]);const p=(await c.query<any>('INSERT INTO customer_payments(customer_id,amount,created_by) VALUES($1,$2,$3) RETURNING *',[id,amount,user.sub])).rows[0];let remaining=amount;const debts=(await c.query<any>(`SELECT id,debt_remaining FROM sales WHERE customer_id=$1 AND status='CONFIRMED' AND debt_remaining>0 ORDER BY created_at,id FOR UPDATE`,[id])).rows;for(const d of debts){if(remaining<=0)break;const used=Math.min(remaining,Number(d.debt_remaining));await c.query('UPDATE sales SET debt_remaining=debt_remaining-$2 WHERE id=$1',[d.id,used]);await c.query('INSERT INTO customer_payment_allocations(payment_id,sale_id,amount) VALUES($1,$2,$3)',[p.id,d.id,used]);remaining-=used;}if(remaining>0)await c.query(`INSERT INTO customer_accounts(customer_id,credit_balance) VALUES($1,$2) ON CONFLICT(customer_id) DO UPDATE SET credit_balance=customer_accounts.credit_balance+EXCLUDED.credit_balance,updated_at=now()`,[id,remaining]);await c.query("INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'CUSTOMER_PAYMENT_RECEIVED','CUSTOMER',$2,$3)",[user.sub,id,JSON.stringify({paymentId:p.id,amount,creditAdded:remaining})]);return {...p,credit_added:remaining};});}
}
