import { BadRequestException,Injectable,NotFoundException } from '@nestjs/common'; import { DatabaseService } from '../database/database.service'; import { PasswordService } from '../auth/password.service'; import { UserRole } from '../auth/auth.types';
@Injectable() export class UsersService { constructor(private db:DatabaseService,private passwords:PasswordService){}
 async create(actorId:string,b:{fullName:string;username:string;password:string;role:UserRole;locationId?:string|null;preferredLanguage?:string}){ if(!String(b.fullName||'').trim()||!String(b.username||'').trim()||!b.password) throw new BadRequestException('Full name, username and password are required'); if((b.role==='BRANCH_USER'||b.role==='STOREKEEPER')&&!b.locationId) throw new BadRequestException('Location is required for Branch User and Storekeeper'); const lang=b.preferredLanguage==='rw'?'rw':'en'; const hash=this.passwords.hash(b.password); try{ const r=await this.db.query<any>('INSERT INTO users(full_name,username,password_hash,role,location_id,preferred_language) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,full_name,username,role,location_id,active,preferred_language',[b.fullName.trim(),b.username.trim(),hash,b.role,b.locationId||null,lang]); await this.audit(actorId,'USER_CREATED',r.rows[0].id,{role:b.role}); return r.rows[0]; }catch(e:any){ if(e?.code==='23505') throw new BadRequestException('Username already exists'); throw e; } }
 async update(actorId:string,id:string,b:any){ const current=(await this.db.query<any>('SELECT * FROM users WHERE id=$1',[id])).rows[0]; if(!current) throw new NotFoundException('User not found'); const fullName=b.fullName===undefined?current.full_name:String(b.fullName).trim(); if(!fullName) throw new BadRequestException('Full name is required'); const role=b.role||current.role; if(!['ADMIN','MANAGER','STOREKEEPER','BRANCH_USER'].includes(role)) throw new BadRequestException('Invalid role'); const locationId=b.locationId===undefined?current.location_id:(b.locationId||null); if((role==='BRANCH_USER'||role==='STOREKEEPER')&&!locationId) throw new BadRequestException('Location is required for Branch User and Storekeeper'); const lang=b.preferredLanguage===undefined?current.preferred_language:(b.preferredLanguage==='rw'?'rw':'en'); const bump=role!==current.role||locationId!==current.location_id; const r=await this.db.query<any>('UPDATE users SET full_name=$2,role=$3,location_id=$4,preferred_language=$5,session_version=session_version+$6,updated_at=now() WHERE id=$1 RETURNING id,full_name,username,role,location_id,active,preferred_language',[id,fullName,role,locationId,lang,bump?1:0]); await this.audit(actorId,'USER_UPDATED',id,{role,locationId}); return r.rows[0]; }
 async list(){ return (await this.db.query<any>('SELECT u.id,u.full_name,u.username,u.role,u.location_id,l.name location_name,u.active,u.preferred_language,u.last_login_at FROM users u LEFT JOIN locations l ON l.id=u.location_id ORDER BY u.full_name NULLS LAST,u.username')).rows; }
 async setActive(actorId:string,id:string,active:boolean){ const r=await this.db.query<any>('UPDATE users SET active=$2,session_version=session_version+1,updated_at=now() WHERE id=$1 RETURNING id,username,active',[id,active]); if(!r.rows[0]) throw new NotFoundException(); await this.audit(actorId,active?'USER_ACTIVATED':'USER_DEACTIVATED',id,{}); return r.rows[0]; }
 async resetPassword(actorId:string,id:string,newPassword:string){ const hash=this.passwords.hash(newPassword); const r=await this.db.query('UPDATE users SET password_hash=$2,password_changed_at=now(),session_version=session_version+1,updated_at=now() WHERE id=$1',[id,hash]); if(!r.rowCount) throw new NotFoundException(); await this.audit(actorId,'PASSWORD_RESET',id,{}); return {ok:true}; }
 async changeOwnPassword(id:string,oldPassword:string,newPassword:string){ const r=await this.db.query<any>('SELECT password_hash FROM users WHERE id=$1 AND active=true',[id]); if(!r.rows[0]||!this.passwords.verify(oldPassword,r.rows[0].password_hash)) throw new BadRequestException('Current password is incorrect'); const hash=this.passwords.hash(newPassword); await this.db.query('UPDATE users SET password_hash=$2,password_changed_at=now(),session_version=session_version+1,updated_at=now() WHERE id=$1',[id,hash]); await this.audit(id,'PASSWORD_CHANGED',id,{}); return {ok:true}; }
 private audit(actor:string,action:string,entity:string,metadata:any){ return this.db.query('INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,\'USER\',$3,$4)',[actor,action,entity,metadata]); }
}
