import { BadRequestException,ForbiddenException,Injectable } from '@nestjs/common'; import { DatabaseService } from '../database/database.service'; import { AuthUser } from '../auth/auth.types';
@Injectable() export class ReportsService{
 constructor(private db:DatabaseService){}
 private loc(user:AuthUser,requested?:string){ if(user.role==='ADMIN') return requested||null; if(!user.locationId) throw new ForbiddenException('No location assigned'); if(requested&&requested!==user.locationId) throw new ForbiddenException('You cannot access another location'); return user.locationId; }
 private dates(q:any){const to=q.to?new Date(q.to):new Date(); const from=q.from?new Date(q.from):new Date(to.getTime()-30*86400000); if(isNaN(+from)||isNaN(+to)||from>to)throw new BadRequestException('Invalid date range'); return [from.toISOString(),to.toISOString()];}
 async dashboard(user:AuthUser,requested?:string){const locationId=this.loc(user,requested);
  if(user.role==='STOREKEEPER') { const r=await this.db.query<any>(`SELECT count(*) FILTER(WHERE status='DRAFT')::int open, count(*) FILTER(WHERE status='COMPLETED' AND match_status='MATCHED')::int matched, count(*) FILTER(WHERE status='COMPLETED' AND match_status='NOT_MATCHED')::int not_matched FROM physical_stock_counts WHERE location_id=$1 AND count_date>=CURRENT_DATE-30`,[locationId]); return {role:user.role,locationId,physicalStock:{open:r.rows[0].open,matched:r.rows[0].matched,notMatched:r.rows[0].not_matched}}; }
  const sales=await this.db.query<any>(`SELECT COALESCE(sum(total),0) total,count(*)::int count FROM sales WHERE status='CONFIRMED' AND created_at>=date_trunc('month',now()) AND ($1::uuid IS NULL OR location_id=$1)`,[locationId]);
  const stock=await this.db.query<any>(`SELECT count(*) FILTER(WHERE quantity=0)::int out_count,count(*) FILTER(WHERE quantity BETWEEN 0.001 AND 50)::int low_count FROM stock_balances WHERE ($1::uuid IS NULL OR location_id=$1)`,[locationId]);
  const base:any={role:user.role,locationId,salesThisMonth:Number(sales.rows[0].total),salesCount:Number(sales.rows[0].count),lowStockCount:Number(stock.rows[0].low_count),outOfStockCount:Number(stock.rows[0].out_count)};
  if(user.role!=='ADMIN') return base;
  const fin=await this.financial(user,{locationId}); const supplier=await this.db.query<any>(`SELECT (SELECT COALESCE(sum(debt_remaining),0) FROM purchases WHERE status='CONFIRMED') debt,(SELECT COALESCE(sum(credit_balance),0) FROM supplier_accounts) credit`);
  return {...base,grossProfit:fin.grossProfit,expenses:fin.expenses,netProfit:fin.netProfit,stockValuation:fin.stockValuation,supplierDebt:Number(supplier.rows[0].debt),supplierCredit:Number(supplier.rows[0].credit)};
 }
 async sales(user:AuthUser,q:any){const locationId=this.loc(user,q.locationId);const [from,to]=this.dates(q);const r=await this.db.query<any>(`SELECT s.sale_number,s.created_at,s.customer_name,s.total,s.cash_paid,s.credit_used,s.debt_remaining,s.status,u.full_name creator,l.name location FROM sales s LEFT JOIN users u ON u.id=s.created_by JOIN locations l ON l.id=s.location_id WHERE s.created_at BETWEEN $1 AND $2 AND ($3::uuid IS NULL OR s.location_id=$3) ORDER BY s.created_at DESC`,[from,to,locationId]);return {from,to,locationId,rows:r.rows};}
 async expenses(user:AuthUser,q:any){const locationId=this.loc(user,q.locationId);const [from,to]=this.dates(q);const r=await this.db.query<any>(`SELECT e.expense_date,e.description,e.amount,l.name location,u.full_name creator FROM expenses e JOIN locations l ON l.id=e.location_id LEFT JOIN users u ON u.id=e.created_by WHERE e.deleted_at IS NULL AND e.created_at BETWEEN $1 AND $2 AND ($3::uuid IS NULL OR e.location_id=$3) ORDER BY e.expense_date DESC,e.created_at DESC`,[from,to,locationId]);return {from,to,locationId,rows:r.rows};}
 async financial(user:AuthUser,q:any){if(user.role!=='ADMIN')throw new ForbiddenException();const locationId=q.locationId||null;const [from,to]=this.dates(q);const s=await this.db.query<any>(`SELECT (SELECT COALESCE(sum(total),0) FROM sales WHERE status='CONFIRMED' AND created_at BETWEEN $1 AND $2 AND ($3::uuid IS NULL OR location_id=$3)) revenue,(SELECT COALESCE(sum(i.cogs),0) FROM sale_items i JOIN sales sx ON sx.id=i.sale_id WHERE sx.status='CONFIRMED' AND sx.created_at BETWEEN $1 AND $2 AND ($3::uuid IS NULL OR sx.location_id=$3)) cogs`,[from,to,locationId]);const e=await this.db.query<any>(`SELECT COALESCE(sum(amount),0) total FROM expenses WHERE deleted_at IS NULL AND created_at BETWEEN $1 AND $2 AND ($3::uuid IS NULL OR location_id=$3)`,[from,to,locationId]);const v=await this.db.query<any>(`SELECT COALESCE(sum(b.quantity*COALESCE(c.weighted_average_cost,0)),0) valuation FROM stock_balances b LEFT JOIN stock_costs c ON c.product_id=b.product_id AND c.location_id=b.location_id WHERE ($1::uuid IS NULL OR b.location_id=$1)`,[locationId]);const revenue=Number(s.rows[0].revenue),cogs=Number(s.rows[0].cogs),expenses=Number(e.rows[0].total);return {from,to,locationId,revenue,cogs,grossProfit:revenue-cogs,expenses,netProfit:revenue-cogs-expenses,stockValuation:Number(v.rows[0].valuation)};}
 async physicalCounts(user:AuthUser,q:any){const locationId=this.loc(user,q.locationId); if(user.role==='STOREKEEPER'){const r=await this.db.query<any>(`SELECT count_date,status,match_status FROM physical_stock_counts WHERE location_id=$1 ORDER BY count_date DESC LIMIT 90`,[locationId]);return {locationId,rows:r.rows};} const r=await this.db.query<any>(`SELECT c.id,c.count_date,c.status,c.match_status,l.name location FROM physical_stock_counts c JOIN locations l ON l.id=c.location_id WHERE ($1::uuid IS NULL OR c.location_id=$1) ORDER BY c.count_date DESC LIMIT 180`,[locationId]);return {locationId,rows:r.rows};}
}
