import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service'; import { AuthUser } from '../auth/auth.types';
@Injectable()
export class PhysicalStockService {
 constructor(private db:DatabaseService){}
 private location(user:AuthUser){if(user.role!=='STOREKEEPER'||!user.locationId) throw new ForbiddenException('Physical stock count is available only to an assigned Storekeeper'); return user.locationId;}
 async startDaily(user:AuthUser){const loc=this.location(user); return this.db.transaction(async c=>{
   const existing=await c.query<any>(`SELECT id,status,match_status,count_date FROM physical_stock_counts WHERE location_id=$1 AND count_date=((now() AT TIME ZONE 'Africa/Kigali')::date)`,[loc]);
   let count=existing.rows[0]; if(!count){const r=await c.query<any>(`INSERT INTO physical_stock_counts(location_id,created_by) VALUES($1,$2) RETURNING id,status,match_status,count_date`,[loc,user.sub]);count=r.rows[0]; await c.query(`INSERT INTO physical_stock_count_items(count_id,product_id) SELECT $1,p.id FROM products p JOIN stock_balances s ON s.product_id=p.id AND s.location_id=$2 WHERE p.active=true ON CONFLICT DO NOTHING`,[count.id,loc]);}
   return {id:count.id,countDate:count.count_date,status:count.status,matchStatus:count.match_status||null};
 });}
 async getDailyForStorekeeper(user:AuthUser){const loc=this.location(user); const r=await this.db.query<any>(`SELECT c.id,c.count_date,c.status,c.match_status,i.product_id,p.name,i.physical_quantity FROM physical_stock_counts c JOIN physical_stock_count_items i ON i.count_id=c.id JOIN products p ON p.id=i.product_id WHERE c.location_id=$1 AND c.count_date=((now() AT TIME ZONE 'Africa/Kigali')::date) ORDER BY p.name`,[loc]); if(!r.rowCount)return null; const head={id:r.rows[0].id,countDate:r.rows[0].count_date,status:r.rows[0].status,matchStatus:r.rows[0].status==='COMPLETED'?r.rows[0].match_status:null}; if(r.rows[0].status==='COMPLETED') return head; return {...head,items:r.rows.map(x=>({productId:x.product_id,name:x.name,physicalQuantity:x.physical_quantity===null?null:Number(x.physical_quantity)}))};}
 async savePhysicalQuantity(user:AuthUser,productId:string,value:any){const loc=this.location(user),q=Number(value); if(!Number.isFinite(q)||q<0)throw new BadRequestException('Physical quantity must be zero or greater'); const r=await this.db.query<any>(`UPDATE physical_stock_count_items i SET physical_quantity=$1,counted_at=now() FROM physical_stock_counts c WHERE i.count_id=c.id AND i.product_id=$2 AND c.location_id=$3 AND c.count_date=((now() AT TIME ZONE 'Africa/Kigali')::date) AND c.status='DRAFT' RETURNING i.product_id`,[q,productId,loc]); if(!r.rowCount)throw new NotFoundException('Open daily count item not found'); return {saved:true,productId,physicalQuantity:q};}
 async completeDaily(user:AuthUser){const loc=this.location(user); return this.db.transaction(async c=>{const cr=await c.query<any>(`SELECT id FROM physical_stock_counts WHERE location_id=$1 AND count_date=((now() AT TIME ZONE 'Africa/Kigali')::date) AND status='DRAFT' FOR UPDATE`,[loc]);if(!cr.rowCount)throw new NotFoundException('Open daily count not found');const id=cr.rows[0].id; const missing=await c.query<any>(`SELECT count(*)::int n FROM physical_stock_count_items WHERE count_id=$1 AND physical_quantity IS NULL`,[id]);if(Number(missing.rows[0].n)>0)throw new BadRequestException('Count every required product before completing the daily report');
 const cmp=await c.query<any>(`SELECT i.product_id,i.physical_quantity,COALESCE(s.quantity,0) system_quantity FROM physical_stock_count_items i LEFT JOIN stock_balances s ON s.product_id=i.product_id AND s.location_id=$2 WHERE i.count_id=$1`,[id,loc]); let matched=true; for(const x of cmp.rows){const sys=Number(x.system_quantity),phy=Number(x.physical_quantity),diff=phy-sys;if(diff!==0){matched=false;await c.query(`INSERT INTO stock_adjustment_reviews(count_id,product_id,system_quantity,physical_quantity,difference) VALUES($1,$2,$3,$4,$5) ON CONFLICT(count_id,product_id) DO UPDATE SET system_quantity=EXCLUDED.system_quantity,physical_quantity=EXCLUDED.physical_quantity,difference=EXCLUDED.difference`,[id,x.product_id,sys,phy,diff]);}}
 const status=matched?'MATCHED':'NOT_MATCHED';await c.query(`UPDATE physical_stock_counts SET status='COMPLETED',match_status=$2,completed_by=$3,completed_at=now() WHERE id=$1`,[id,status,user.sub]); return {id,status:'COMPLETED',matchStatus:status};});}
 async adminDetail(user:AuthUser,countId:string){if(user.role!=='ADMIN')throw new ForbiddenException();const r=await this.db.query<any>(`SELECT c.id,c.count_date,c.status,c.match_status,l.name location_name,p.id product_id,p.name,i.physical_quantity,COALESCE(s.quantity,0) current_system_quantity,ar.system_quantity system_quantity_at_completion,ar.difference,ar.status review_status FROM physical_stock_counts c JOIN locations l ON l.id=c.location_id JOIN physical_stock_count_items i ON i.count_id=c.id JOIN products p ON p.id=i.product_id LEFT JOIN stock_balances s ON s.product_id=p.id AND s.location_id=c.location_id LEFT JOIN stock_adjustment_reviews ar ON ar.count_id=c.id AND ar.product_id=p.id WHERE c.id=$1 ORDER BY p.name`,[countId]);if(!r.rowCount)throw new NotFoundException('Count not found');return r.rows;}
 async adjust(user:AuthUser,countId:string,productId:string,reason:'DAMAGE'|'MISSING_LOSS'){if(user.role!=='ADMIN')throw new ForbiddenException();if(!['DAMAGE','MISSING_LOSS'].includes(reason))throw new BadRequestException('Reason must be DAMAGE or MISSING_LOSS');return this.db.transaction(async c=>{const r=await c.query<any>(`SELECT ar.difference,c.location_id FROM stock_adjustment_reviews ar JOIN physical_stock_counts c ON c.id=ar.count_id WHERE ar.count_id=$1 AND ar.product_id=$2 AND ar.status='PENDING' FOR UPDATE`,[countId,productId]);if(!r.rowCount)throw new NotFoundException('Pending discrepancy not found');const diff=Number(r.rows[0].difference),loc=r.rows[0].location_id;if(diff===0)throw new ConflictException('No discrepancy to adjust');await c.query('INSERT INTO stock_balances(product_id,location_id,quantity) VALUES($1,$2,0) ON CONFLICT DO NOTHING',[productId,loc]);const b=await c.query<any>('SELECT quantity FROM stock_balances WHERE product_id=$1 AND location_id=$2 FOR UPDATE',[productId,loc]);const before=Number(b.rows[0].quantity),after=before+diff;if(after<0)throw new ConflictException('Adjustment would create negative stock; Admin review is required');const movementType=diff>0?'ADJUSTMENT_IN':'ADJUSTMENT_OUT';const mv=await c.query<any>(`INSERT INTO stock_movements(product_id,location_id,movement_type,quantity,quantity_before,quantity_after,source_type,source_id,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,'PHYSICAL_COUNT',$7,$8,$9) RETURNING id`,[productId,loc,movementType,Math.abs(diff),before,after,countId,reason,user.sub]);await c.query('UPDATE stock_balances SET quantity=$3,updated_at=now() WHERE product_id=$1 AND location_id=$2',[productId,loc,after]);await c.query(`UPDATE stock_adjustment_reviews SET status='ADJUSTED',resolution_reason=$3,resolved_by=$4,resolved_at=now() WHERE count_id=$1 AND product_id=$2`,[countId,productId,reason,user.sub]);await c.query(`INSERT INTO audit_events(actor_user_id,action,entity_type,entity_id,location_id,metadata) VALUES($1,'PHYSICAL_STOCK_ADJUSTED','PHYSICAL_COUNT',$2,$3,$4::jsonb)`,[user.sub,countId,loc,JSON.stringify({productId,reason,difference:diff,movementId:mv.rows[0].id})]);return {adjusted:true,movementId:mv.rows[0].id};});}
}
